### ISSUE TITLE
Buffer size too short

### ISSUE THREAD

**Issue by ramonmedeiros** [famz/patchew#2]
Hi,

after loading patches from my ML, the buffer size did not support it:

OperationFailure: database error: Runner error: Overflow sort stage buffered data usage of 33560568 bytes exceeds internal limit of 33554432 bytes

I saw that we can change it by adding: 
http://askubuntu.com/questions/501937/how-to-increase-buffered-data-limit

**Comment by famz** [comment]
Can you figure out which operation is this in patchew? Is there a backtrace?

**Comment by ramonmedeiros** [comment]
Yeah:

[root@happy libpatchew]# patchew server
None
server.conf
/etc/patchew/server.conf
Bottle v0.12.6 server starting up (using CherryPyServer())...
Listening on http://0.0.0.0:8383/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/bottle.py", line 1727, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/site-packages/libpatchew/server.py", line 267,
in view_index
    totalpages = (db.find_series_count(query=query) - 1) / pagesize + 1
  File "/usr/lib/python2.7/site-packages/libpatchew/db.py", line 275, in
find_series_count
    for i in self._find_series_iter(query=query):
  File "/usr/lib/python2.7/site-packages/libpatchew/db.py", line 260, in
_find_series_iter
    for i in self._messages.find(q, sort=sort):
  File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 814, in
next
    if len(self.__data) or self._refresh():
  File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 763, in
_refresh
    self.__uuid_subtype))
  File "/usr/lib64/python2.7/site-packages/pymongo/cursor.py", line 720, in
__send_message
    self.__uuid_subtype)
  File "/usr/lib64/python2.7/site-packages/pymongo/helpers.py", line 100,
in _unpack_response
    error_object["$err"])
OperationFailure: database error: Runner error: Overflow sort stage
buffered data usage of 33560568 bytes exceeds internal limit of 33554432
bytes


On Wed, Apr 13, 2016 at 11:13 PM, Fam Zheng <notifications@github.com>
wrote:

> Can you figure out which operation is this in patchew? Is there a
> backtrace?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/famz/patchew/issues/2#issuecomment-209723903>
>



-- 
Ramon Nunes Medeiros

GitHub: https://github.com/ramonmedeiros
Linkedin: http://www.linkedin.com/pub/ramon-medeiros/22/8aa/245

**Comment by famz** [comment]
We can try to make the find_series_count release the object earlier and hopefully the database can also free the buffer.

**Comment by famz** [comment]
I'm not a mongodb guru and don't really understand why the created index on the 'date' key is insufficient. What is the size of your "messages" collection? It would be great if you could provide a way to reproduce so I can find a fix.

**Comment by famz** [comment]
@ramonmedeiros could you try again with current master? (https://github.com/famz/patchew/commit/9c717b69385e2febe4919dd3da900e29deef0331)

**Comment by ramonmedeiros** [comment]
@famz working perfectly. Thanks
